features/advantages
evglitik/team-prodject-4 pull request #3
Opened 2022-04-02 11:24 UTC by dmytrokravchenko1

add advantages

2022-04-02 15:11 UTC, evglitik requested changes

2022-04-02 15:11 UTC, evglitik commented on src/sass/components/_container.scss
> +        width: 738px;
почему 738?

2022-04-02 15:11 UTC, evglitik commented on src/partials/advantages.html
> +                <span class="advantages-number advantages-number__heart">84</span>
Тут с классами что то. Я думаю, что 84 не может быть отдельным блоком, только как элемент. (по БЭМ) Предлагаю лижку оставить блоком, а "p" "span" элементами оставить классы

2022-04-03 15:01 UTC, dmytrokravchenko1 commented on src/partials/advantages.html
> +                <span class="advantages-number advantages-number__heart">84</span>
пересмотрел классы

2022-04-03 15:02 UTC, dmytrokravchenko1 commented on src/sass/components/_container.scss
> +        width: 738px;
вернул обратно

2022-04-03 15:13 UTC, closed without merging